#cloud-config

coreos:
  units:
    - name: kubelet.service
      command: start
      content: |
        [Unit]
        After=opt-kubernetes.mount etcd.service docker.socket
        ConditionFileIsExecutable=/opt/kubernetes/bin/kubelet
        Description=Kubernetes Kubelet
        Documentation=https://github.com/GoogleCloudPlatform/kubernetes
        Requires=opt-kubernetes.mount etcd.service docker.socket

        [Service]
        ExecStart=/opt/kubernetes/bin/kubelet \
        --address=0.0.0.0 \
        --hostname_override=${MINION_IPS[$i]} \
        --etcd_servers=http://127.0.0.1:4001
        Restart=always
        RestartSec=2

        [Install]
        WantedBy=multi-user.target
    - name: kube-proxy.service
      command: start
      content: |
        [Unit]
        After=opt-kubernetes.mount etcd.service
        ConditionFileIsExecutable=/opt/kubernetes/bin/kube-proxy
        Description=Kubernetes Proxy
        Documentation=https://github.com/GoogleCloudPlatform/kubernetes
        Requires=opt-kubernetes.mount etcd.service

        [Service]
        ExecStart=/opt/kubernetes/bin/kube-proxy \
        --etcd_servers=http://127.0.0.1:4001 \
        --master=http://${MASTER_IP}:7080
        Restart=always
        RestartSec=2

        [Install]
        WantedBy=multi-user.target
